# Generated by Django 4.1.7 on 2023-03-15 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '__first__'),
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateField()),
                ('status', models.BooleanField()),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locador')),
                ('objeto_emprestimo', models.ManyToManyField(related_name='objetos', to='objetos.objetos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
